---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "hello-world"

---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "hello-world"
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "https://github.com/qh-hale/test-nginx.git"
    targetRevision: "HEAD"
    path: "hello-world"
    helm:
      valueFiles:
        - "secrets.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "hello-world"
