apiVersion:  argoproj.io/v1alpha1
kind:  Application
metadata:  
  name:  testapp 
  namespace:  test1
spec:  
  project:  default
  source:  
    repoURL: https://github.com/qh-hale/test-nginx.git   
    targetRevision:  master
    path:  nginx/
    helm:
      releaseName: testapp
      valueFiles:
        - "values.yaml"
  destination:  
    server:  https://kubernetes.default.svc
    namespace:  test1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
